// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos(id, created_at, updated_at, title, description, duration_seconds)
VALUES (gen_random_uuid(), NOW(), NOW(), $1, $2, $3)
RETURNING id, created_at, updated_at, title, description, duration_seconds
`

type CreateVideoParams struct {
	Title           string
	Description     string
	DurationSeconds int32
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo, arg.Title, arg.Description, arg.DurationSeconds)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.DurationSeconds,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, created_at, updated_at, title, description, duration_seconds FROM videos
WHERE id=$1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.DurationSeconds,
	)
	return i, err
}
